package com.hoanglm.flutteryoutubeview

enum class PlayerError(val value: String) {
    UNKNOWN("UNKNOWN"),
    INVALID_PARAMETER_IN_REQUEST("INVALID_PARAMETER_IN_REQUEST"),
    HTML_5_PLAYER("HTML_5_PLAYER"),
    VIDEO_NOT_FOUND("VIDEO_NOT_FOUND"),
    VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER("VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER")
}